# Generated by Django 3.0.3 on 2020-02-24 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task_runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
