# Generated by Django 3.0.3 on 2020-02-20 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
