# Generated by Django 3.0.3 on 2020-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
