# Generated by Django 3.0.3 on 2020-02-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20200220_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
