# Generated by Django 3.0.3 on 2020-02-25 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20200222_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='created_date',
        ),
        migrations.AddField(
            model_name='table',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
